version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: gitsubmodule
    directory: "{resources}/test/JSON-Schema-Test-Suite"
    schedule:
      interval: daily
