name: test
on:
- push
- pull_request
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
        - jruby
        - truffleruby
        - truffleruby+graalvm
        - '2.3'
        - '2.7'
        - '3.0'
        - head
        runs-on:
        - ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    env:
      BUNDLE_WITHOUT: dev # ruby/setup-ruby's invocation of bundle install will be without the `dev` group

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: bundle exec rake test

    - name: Report to Coveralls
      uses: coverallsapp/github-action@v2.1.1
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: "test ruby: ${{ matrix.ruby-version }} os: ${{ matrix.runs-on }}"
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:

    - name: Report completion to Coveralls
      uses: coverallsapp/github-action@v2.1.1
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
