name: test
on:
- push
- pull_request
jobs:
  gig:
    runs-on: ubuntu-latest

    env:
      BUNDLE_WITHOUT: dev test extdep doc # ruby/setup-ruby's invocation of bundle install will be without these groups

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: head
        bundler-cache: true

    - run: bundle exec rake gig

  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
        - jruby
        - truffleruby
        - truffleruby+graalvm
        - '2.3'
        - '2.7'
        - '3.0'
        - ruby # latest release
        #- head # commented for 3.5.0dev pending https://bugs.ruby-lang.org/issues/21375
        runs-on:
        - ubuntu-latest

    runs-on: ${{ matrix.runs-on }}

    env:
      BUNDLE_WITHOUT: dev doc # ruby/setup-ruby's invocation of bundle install will be without these groups

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: "if (( RANDOM % 2 )); then bin/chkbug.rb; fi"

    - run: bundle exec rake test

    - run: bundle exec ruby readme.rb

    - name: Report to Coveralls
      uses: coverallsapp/github-action@v2.3.6
      with:
        github-token: ${{ secrets.github_token }}
        flag-name: "test ruby: ${{ matrix.ruby-version }} os: ${{ matrix.runs-on }}"
        parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:

    - name: Report completion to Coveralls
      uses: coverallsapp/github-action@v2.3.6
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
